### ISSUE TITLE
Jump_List_JL_Ad error

### ISSUE THREAD

**Issue by reineckejd** [markmckinnon/Autopsy-Plugins#32]
Hi,

I am running Autopsy 4.14 on Tsurugi, and am trying to parse a Windows image just runing the Jump_List module.  getting the following error:
Traceback (most recent call last):
  File "/root/.autopsy/dev/python_modules/Jump_List_AD/JumpList_AD.py", line 303, in process
    output = subprocess.Popen([self.path_to_exe, temp_dir, os.path.join(Temp_Dir, "JL_AD.db3"), self.path_to_app_id_db], stdout=subprocess.PIPE).communicate()[0]
  File "/opt/autopsy/autopsy/modules/ext/jython-standalone-2.7.0.jar/Lib/subprocess.py", line 830, in __init__
  File "/opt/autopsy/autopsy/modules/ext/jython-standalone-2.7.0.jar/Lib/subprocess.py", line 1352, in _execute_child
OSError: Cannot run program "/root/.autopsy/dev/python_modules/Jump_List_AD/Export_JL_Ad" (in directory "/home/jon"): error=13, Permission denied

**Comment by reineckejd** [comment]
NVM.  Turns out it is a permissions issue.  chmod x+u against the entire plug in directory fixed it.
